CretaceousClient/Models/Animal.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CretaceousClient.Models
{
	public class Animal
	{
		public int AnimalId { get; set; }
		public string Name { get; set; }
		public string Species { get; set; }
		public int Age { get; set; }
		public string Gender { get; set; }

		public static List<Animal> GetAnimals()
		{
			Task<string> apiCallTask = ApiHelper.GetAll();
			string result = apiCallTask.Result;

			JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
			List<Animal> animalList = JsonConvert.DeserializeObject<List<Animal>>(jsonResponse.ToString());

			return animalList;
		}

		public static Animal GetDetails(int id)
		{
			Task<string> apiCallTask = ApiHelper.Get(id);
			string result = apiCallTask.Result;

			JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
			Animal animal = JsonConvert.DeserializeObject<Animal>(jsonResponse.ToString());

			return animal;
		}

		public static void Post(Animal animal)
		{
			string jsonAnimal = JsonConvert.SerializeObject(animal);
			ApiHelper.Post(jsonAnimal);
		}

		public static void Put(Animal animal)
		{
			string jsonAnimal = JsonConvert.SerializeObject(animal);
			ApiHelper.Put(animal.AnimalId, jsonAnimal);
		}

		public static void Delete(int id)
		{
			ApiHelper.Delete(id);
		}
	}
}

CretaceousClient/Models/ApiHelper.cs
using RestSharp;
using System.Threading.Tasks;

namespace CretaceousClient.Models
{
	class ApiHelper
	{
		public static async Task<string> GetAll()
		{
			RestClient client = new RestClient("http://localhost:5004/api");
			RestRequest request = new RestRequest($"animals", Method.GET);
			IRestResponse response = await client.ExecuteTaskAsync(request);
			return response.Content;
		}

		public static async Task<string> Get(int id)
		{
			RestClient client = new RestClient("http://localhost:5004/api");
			RestRequest request = new RestRequest($"animals/{id}", Method.GET);
			IRestResponse response = await client.ExecuteTaskAsync(request);
			return response.Content;
		}

		public static async Task Post(string newAnimal)
		{
			RestClient client = new RestClient("http://localhost:5004/api");
			RestRequest request = new RestRequest($"animals", Method.POST);
			request.AddHeader("Content-Type", "application/json");
			request.AddJsonBody(newAnimal);
			IRestResponse response = await client.ExecuteTaskAsync(request);
		}

		public static async Task Put(int id, string newAnimal)
		{
			RestClient client = new RestClient("http://localhost:5004/api");
			RestRequest request = new RestRequest($"animals/{id}", Method.PUT);
			request.AddHeader("Content-Type", "application/json");
			request.AddJsonBody(newAnimal);
			IRestResponse response = await client.ExecuteTaskAsync(request);
		}

		public static async Task Delete(int id)
		{
			RestClient client = new RestClient("http://localhost:5004/api");
			RestRequest request = new RestRequest($"animals/{id}", Method.DELETE);
			request.AddHeader("Content-Type", "application/json");
			IRestResponse response = await client.ExecuteTaskAsync(request);
		}
	}
}

CretaceousClient/Controllers/AnimalsController.cs
using CretaceousClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CretaceousClient.Controllers
{
	public class AnimalsController : Controller
	{
		// GET /animals
		public IActionResult Index()
		{
			List<Animal> allAnimals = Animal.GetAnimals();
			return View(allAnimals);
		}

		public IActionResult Details(int id)
		{
			Animal animal = Animal.GetDetails(id);
			return View(animal);
		}
	}
}

CretaceousClient/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CretaceousClient.Controllers
{
	public class HomeController : Controller
	{
		[HttpGet("/")]
		public ActionResult Index()
		{
			return View();
		}
	}
}

CretaceousClient/Views/Animals/Details.cshtml
@model CretaceousClient.Models.Animal

@{
	Layout = "_Layout";
}

<h1 id="title">Animal Details</h1>

<hr />

<p>
	<u><h3>@Model.Name</h3></u>
	<h4><b>Species:</b> @Model.Species</h4>
	<h4><b>Gender:</b> @Model.Gender</h4>
	<h4><b>Age:</b> @Model.Age</h4>
	<h4><b>ID:</b> @Model.AnimalId</h4>
</p>

CretaceousClient/Views/Animals/Index.cshtml
@using CretaceousClient.Models

@{
	Layout = "_Layout";
}

<h1 id="title">Animals</h1>

<hr />
<ol>
  @foreach (Animal animal in Model)
  {
    <ul>
      <li>ID: @animal.AnimalId</li>
      <li>Name: @animal.Name</li>
      <li>Species: @animal.Species</li>
      <li>Age: @animal.Age</li>
      <li>Gender: @animal.Gender</li>
    </ul>
    <a href="/Animals/Details/@(animal.AnimalId)"><p>View Details</p></a>
    <br>
  }
</ol>

CretaceousClient/Views/Home/Index.cshtml
@{
	Layout = "_Layout";
}

<h1 id="title">Cretaceous Client</h1>

<hr />

<p>
	@Html.ActionLink("View all animals", "Index", "Animals")
</p>

CretaceousClient/Views/Shared/Footer.cshtml
<div id="footer">Made with ❤️ by <b>Chris Ramer (Chris is Awesome)</b> | Proudly hosted on <a href="https://github.com/ChrisRamer/new-api-template-site">GitHub</a></div>

CretaceousClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>Cretaceous Client</title>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
	<link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
	@RenderBody()
	@Html.Partial("Footer")
</body>

</html>